name: Tests CI

on:
  push:
  pull_request:

env:
  JDK-version: '8'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{env.JDK-version}}
      - name: compile
        run: ./gradlew clean compileJava
      - name: test
        run: ./gradlew clean test
