name: Tests CI

on:
  push:
  pull_request:

env:
  JDK-version: '15-ea'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{env.JDK-version}}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
      
      - name: Compile java
        run: ./gradlew clean compileJava
      - name: Run tests
        run:
          ./gradlew clean test